name: ShinyUtilities
main: com.hotmail.shinyclef.shinyutilities.ShinyUtilities
version: 1.1.2
commands:
    mute:
        description: Mutes the selected player.
        usage: /<command> [playername]
    unmute:
        description: Mutes the selected player.
        usage: /<command> [playername]
    mutelist:
        description: Displays a list of muted players.
        usage: /<command>
    busy:
        description: Toggles busy mode, which blocks incoming private messages and notifies sender.
        usage: /<command> (optional busy message)
    bookimport:
        description: Creates a book from the specified text file.
        usage: /bookimport [url to .txt file]  eg. /bookimport http://www.mysite.com/book.txt